apiVersion: v1
kind: Service
metadata:
  name: py-kms-loadbalancer
  namespace: default
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: py-kms
  uid: d13efe75-b939-447f-a33f-5160bc9860c5
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.17.254
  clusterIPs:
    - 10.43.17.254
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp1688
      nodePort: 30580
      port: 1688
      protocol: TCP
      targetPort: 1688
    - name: tcp8080
      nodePort: 32578
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-py-kms
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 10.9.15.100
